### ISSUE TITLE
Large data set test on the full stack

### ISSUE THREAD

**Issue by danielfdsilva** [WorldBank-Transport/ram-deployment#25]
While testing the full RAM stack on AWS some problems came up when using a large dataset.
Follow the findings so far to keep track.

### Running on AWS

The data used can be found in this [drive directory](https://drive.google.com/drive/u/1/folders/12SUb3kxyyVuyjzPyRCBYb826ttwbwd4E).

Uploading all the source data through the project setup page works well, and starting the project setup process triggers the start of the FARGATE instances.
We had to increase the memory and CPU of these instances (2048/8GB) otherwise they would be killed with `Out of memory`.

The vector tiles for the `admin-bounds` processes well but fails when uploading to S3:
Cloudwatch stream: https://us-east-1.console.aws.amazon.com/cloudwatch/home?region=us-east-1#logEventViewer:group=ram-demo-test-cf-4-logs;stream=ecs/ram-vt/59203f01-3d03-4a7b-8881-03c7ac3a8389
```
[16:44:34.294] [main] Clean files...
[16:44:34.411] [main] Clean files... done
[16:44:34.411] [main] Downloading admin-bounds...
[16:44:34.524] [main] Downloading admin-bounds... done
[16:44:34.525] [generateVT] Generation started
[16:45:06.268] [generateVT] Completed in 31.743 seconds
[16:45:06.269] [main] Uploading tiles to s3...
error { S3Error: We encountered an internal error. Please try again.
at Object.parseError (/code/node_modules/minio/dist/main/xml-parsers.js:56:11)
at /code/node_modules/minio/dist/main/transformers.js:117:22
at DestroyableTransform._flush (/code/node_modules/minio/dist/main/transformers.js:48:26)
at DestroyableTransform.<anonymous> (/code/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:135:12)
at Object.onceWrapper (events.js:313:30)
at emitNone (events.js:111:20)
at DestroyableTransform.emit (events.js:208:7)
at finishMaybe (/code/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:371:12)
at endWritable (/code/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:378:3)
at DestroyableTransform.Writable.end (/code/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:356:5)
at IncomingMessage.onend (_stream_readable.js:595:10)
at Object.onceWrapper (events.js:313:30)
at emitNone (events.js:111:20)
at IncomingMessage.emit (events.js:208:7)
at endReadableNT (_stream_readable.js:1064:12)
at _combinedTickCallback (internal/process/next_tick.js:139:11)
code: 'InternalError',
requestid: '43ED999EBFC90341',
hostid: 'uhY7HnvD4fIO/XRNu4JpE0tVM9RflNeLUtWRUFEFA1BpGOuUfeI5p1fsuaLcmfFjMaHZqjcG1DI=',
amzRequestid: null,
amzId2: null,
amzBucketRegion: null }
```

The vector tiles for the `road-network` fails when processing the features:
Cloudwatch stream: https://us-east-1.console.aws.amazon.com/cloudwatch/home?region=us-east-1#logEventViewer:group=ram-demo-test-cf-4-logs;stream=ecs/ram-vt/dcc739ec-da1b-4a4f-bcf9-60d2784bb8c6
```
[16:44:35.333] [main] Clean files...
[16:44:35.479] [main] Clean files... done
[16:44:35.480] [main] Downloading/Converting rn to geoJSON...
[16:45:00.514] [osmToGeoJSON] Generation started
[16:48:29.205] [osmToGeoJSON] Completed in 208.691 seconds
[16:48:29.206] [main] Downloading/Converting rn to geoJSON... done
[16:48:29.206] [generateVT] Generation started
error Error: Warning: Can't represent non-numeric feature ID "way/27933877"
Read 0.00 million ... (continues)
0.1% 0/0/0 ... (continues)
Try using --drop-fraction-as-needed or --drop-densest-as-needed.
tile 4/8/7 size is 839300 with detail 11, >500000 
26.6% 4/8/7 ... (continues)
*** NOTE TILES ONLY COMPLETE THROUGH ZOOM 3 ***
Internal error: did not close all files: 4
at /code/app/index.js:156:32
at ChildProcess.exithandler (child_process.js:283:5)
at emitTwo (events.js:126:13)
at ChildProcess.emit (events.js:214:7)
at maybeClose (internal/child_process.js:915:16)
at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
```

The api cloudwatch stream is here: https://us-east-1.console.aws.amazon.com/cloudwatch/home?region=us-east-1#logEventViewer:group=ram-demo-test-cf-4-logs;stream=ecs/ram-api/17b0c3d0-1f7c-44e5-9aee-830e20ba938c

This is the data used by Li and supposedly it worked when using `hyper`, however:
- [x] Try with the data uploaded to the old instance (search for it on S3)

### Running locally

Since it was not working on AWS I tried to run this locally using the S3 bucket as a storage.
This breaks even before getting to the vector tiles generation as the road-network upload fails with:

```
Debug: received
    {"method":"post","url":"/projects/27/scenarios/35/source-data","agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:64.0) Gecko/20100101 Firefox/64.0"}
error { Error: ENOENT: no such file or directory, open '/var/folders/bz/hbd_z7ts11z8qswbsjqdnhc80000gn/T/4Eo7G8hQJVfGEJd9thoF3Csh.osm'
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/var/folders/bz/hbd_z7ts11z8qswbsjqdnhc80000gn/T/4Eo7G8hQJVfGEJd9thoF3Csh.osm' }
Debug: handler, error
    {"msec":139216.4866899997,"error":"ENOENT: no such file or directory, open '/var/folders/bz/hbd_z7ts11z8qswbsjqdnhc80000gn/T/4Eo7G8hQJVfGEJd9thoF3Csh.osm'","data":{"errno":-2,"code":"ENOENT","syscall":"open","path":"/var/folders/bz/hbd_z7ts11z8qswbsjqdnhc80000gn/T/4Eo7G8hQJVfGEJd9thoF3Csh.osm","isBoom":true,"isServer":true,"output":{"statusCode":500,"payload":{"statusCode":500,"error":"Internal Server Error","message":"An internal server error occurred"},"headers":{}},"isDeveloperError":true}}
181221/174318.084, [response] http://0.0.0.0:4000: post /projects/27/scenarios/35/source-data {} 200 (139222ms)
error { Error: ENOENT: no such file or directory, open '/var/folders/bz/hbd_z7ts11z8qswbsjqdnhc80000gn/T/UkCdHzJtl0-gTZdlV8sr70kb.osm'
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/var/folders/bz/hbd_z7ts11z8qswbsjqdnhc80000gn/T/UkCdHzJtl0-gTZdlV8sr70kb.osm' }
Debug: handler, error
    {"msec":138947.1693169996,"error":"ENOENT: no such file or directory, open '/var/folders/bz/hbd_z7ts11z8qswbsjqdnhc80000gn/T/UkCdHzJtl0-gTZdlV8sr70kb.osm'","data":{"errno":-2,"code":"ENOENT","syscall":"open","path":"/var/folders/bz/hbd_z7ts11z8qswbsjqdnhc80000gn/T/UkCdHzJtl0-gTZdlV8sr70kb.osm","isBoom":true,"isServer":true,"output":{"statusCode":500,"payload":{"statusCode":500,"error":"Internal Server Error","message":"An internal server error occurred"},"headers":{}},"isDeveloperError":true}}
181221/174531.366, [response] http://0.0.0.0:4000: post /projects/27/scenarios/35/source-data {} 200 (138950ms)
```

I'm not sure what is happening here but when looking at the temporary directory where the file is, I noticed that after some time its name changes.
I think it may have something to do with the way Hapi deals with multipart streams. Things to try:
- [x] Double check how the file is uploaded to the server and then to s3.
- [x] Investigate other methods of uploading the file to the server while keeping the other form data.

cc @olafveerman

**Comment by danielfdsilva** [comment]
For some unknown reason the file name changed during the upload process causing it to fail. Implemented a different method of upload to fix this.
